# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
# Манифест для развертывания (Манифест 1)
# Created with podman-5.5.2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybot-deployment
  labels:
    app: mybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mybot
  template:
    metadata:
      labels:
        app: mybot
    spec:
      imagePullSecrets:
        - name: quayio-secret
      containers:
        - name: mybot
          image: quay.io/nikolasheva/my-bot:v2
          envFrom:
            - secretRef:
                name: mybot-secrets
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
        